### ISSUE TITLE
survival players can't break any blocks.

### ISSUE THREAD

**Issue by CaryCatZ** [KenRouKoro/MCMTFabricCE#11]
As title, survival players can not break blocks, but creative players can.

Minecraft Server 1.19
Mod list:
 - alternate-current-mc1.19-1.4.0
 - badpackets-fabric-0.1.2-MC1.19
 - BowInfinityFix-1.19.x-fabric-2.5.0
 - carpet-extra-1.19-1.4.79
 - carpet-tis-addition-mc1.19-v1.38.0
 - cloth-api-4.0.65
 - cloth-config-7.0.74-fabric-MC1.19
 - fabric-api-0.57.0+1.19
 - fabric-carpet-1.19-1.4.79+v220607
 - ftbbackups2-forge-1.19.2-1.0.13
 - mcmtce-2.0.0-ex-beta1-MC1.19
 - NoChatReports-FABRIC-1.19-v1.2.3
 - no-telemetry-1.4.0
 - servux-fabric-1.19.0-0.1.0
 - starlight-1.1.1+fabric.ae22326

**Comment by Zhang32767** [comment]
And, it is probabilistic. Sometimes we can, sometimes we can't

**Comment by CaryCatZ** [comment]
Log:
[latest.log](https://github.com/KenRouKoro/MCMTFabricCE/files/9639242/latest.log)
The game shall crash, but it dosen't.
It's just keep running.

**Comment by KenRouKoro** [comment]
1.19版本是不含任何兼容代码的，它的兼容性和mcmtfabric在1.18的表现一致
