### ISSUE TITLE
[Suggestion] Discussions with dev of C2ME (Ishland)

### ISSUE THREAD

**Issue by StockiesLad** [KenRouKoro/MCMTFabricCE#2]
Discussion between you guys and Ishland could lead to ensuring compat between C2ME as well as helping eachother out improving the Internal Server Peformance.

**Comment by StockiesLad** [comment]
https://discord.gg/Kdy8NM5HW4 Here is an invite link to the server if this is approved of.

**Comment by KenRouKoro** [comment]
Thank you very much for the error log report and I will target its response for immediate fix.
I would also like to make a few suggestions regarding the logs you provided.
Firstly, please use UTF-8 as the encoding for your console, as most error messages are in Chinese and I use UTF-8 encoding.
Secondly, please try to avoid using this module on the Minecraft client, as it makes some of the client modules think it is working on the server.
Also, I have stated in the README that it is not compatible with C2ME and that at this stage C2ME and MCMT have duplicated functionality.
Finally, some personal thoughts on the compatibility of the C2ME module.
This project is still in its early stages and I am the only one working on it (this project is a spin-off from MCMTFabric), compatibility with many modules is already consuming a lot of my energy (I am a second year Chinese university student with many research projects to complete) and compatibility with C2ME is a very difficult task. I need more time and some help to complete this task.

**Comment by StockiesLad** [comment]
> Thank you very much for the error log report and I will target its response for immediate fix. I would also like to make a few suggestions regarding the logs you provided. Firstly, please use UTF-8 as the encoding for your console, as most error messages are in Chinese and I use UTF-8 encoding. Secondly, please try to avoid using this module on the Minecraft client, as it makes some of the client modules think it is working on the server. Also, I have stated in the README that it is not compatible with C2ME and that at this stage C2ME and MCMT have duplicated functionality. Finally, some personal thoughts on the compatibility of the C2ME module. This project is still in its early stages and I am the only one working on it (this project is a spin-off from MCMTFabric), compatibility with many modules is already consuming a lot of my energy (I am a second year Chinese university student with many research projects to complete) and compatibility with C2ME is a very difficult task. I need more time and some help to complete this task.

Thank you for your response. I will take all this into consideration!

**Comment by StockiesLad** [comment]
This thread is more of just a Future plan kind of thing. Parity with C2ME would be insanely difficult and the last thing I want is to rush you. Take all the time you need.

**Comment by qb20nh** [comment]
My understanding is that C2ME is mainly focused on improving chunk generation/load performance in which includes parallelized world generation and loading and whatnot, and this mod parallelizes all iterative ticking operations including entities and tile entities. Apparently C2ME does A LOT under the hood so I see that some parts of these mods functionality can conflict with each other.

**Comment by KenRouKoro** [comment]
> My understanding is that C2ME is mainly focused on improving chunk generation/load performance in which includes parallelized world generation and loading and whatnot, and this mod parallelizes all iterative ticking operations including entities and tile entities. Apparently C2ME does A LOT under the hood so I see that some parts of these mods functionality can conflict with each other.

So, I'm writing a new Mod for Entities concurrent operations only. This is because there are other Mods that implement block loading better, and for block concurrent tick operations the gain is very low (most of the block operations are actually block Entity operations).

**Comment by KenRouKoro** [comment]
I've given up working on MCMTCE compatibility with C2ME, because from the implementation principle MCMTCE is incompatible with C2ME. You can use my new mod, which is fully compatible with C2ME and should work well on the server.
https://github.com/KenRouKoro/C3H6N6O6
