### ISSUE TITLE
DataPack Error

### ISSUE THREAD

**Issue by ardissaps** [KenRouKoro/MCMTFabricCE#7]
![image](https://user-images.githubusercontent.com/82106625/175810450-c427ec7e-8a28-426a-9d48-2e29dd7026af.png)

https://paste.atlauncher.com/view/a1f4f342-73ae-48cb-b421-800c9fdb6ce8

**Comment by KenRouKoro** [comment]
From the log you provided, I found a few things wrong with it.
1. c2me installed (this has been marked as incompatible in readme)
2. The packets and BYG had a bit of a problem with BetterEnd and couldn't find some objects.

**Comment by ardissaps** [comment]
When I tested I disabled C2ME, the log is from multiple session it is whole log from many plays. 1.18.2
I see for point 2, ok.

I tested again on 1.19 with [vulkan rendering](https://modrinth.com/mod/vulkanmod), it stuck on 100% progress loading. but I'll try again
