### ISSUE TITLE
1.18.2fabric服务器无法使用MCMTCE

### ISSUE THREAD

**Issue by esunyao** [KenRouKoro/MCMTFabricCE#9]
[latest.log](https://github.com/KenRouKoro/MCMTFabricCE/files/9243420/latest.log)
[crash-2022-08-02_17.12.39-server.txt](https://github.com/KenRouKoro/MCMTFabricCE/files/9243421/crash-2022-08-02_17.12.39-server.txt)

在使用MCMTCE时，只要玩家一进入服务器，服务器立马就会崩掉(config为默认设定时也会崩)，请问这怎么解决啊。。
这是我的log和crash日志，请帮我看看谢谢。
![image](https://user-images.githubusercontent.com/56782218/182409102-a121c3a4-f047-4ef9-a15b-d40c63922c40.png)
![image](https://user-images.githubusercontent.com/56782218/182409157-c2c43751-9399-4953-a7b7-d48eed0389cf.png)
这是我的mod列表
各个版本的MCMTCE都试了

**Comment by KenRouKoro** [comment]
动了区块的mod基本都不兼容（c2me，平滑区块保存，chunky等）

**Comment by esunyao** [comment]
> 动了区块的mod基本都不兼容（c2me，平滑区块保存，chunky等）

那删掉mod之后就可以了吗？

**Comment by esunyao** [comment]
> 动了区块的mod基本都不兼容（c2me，平滑区块保存，chunky等）

我删除了其它mod，只留下了mcmtce，但是当玩家进入世界时，服务器就会崩溃
